namespace ForestTails.Shared.Enums
{
    public enum MessageCode
    {
        None = 0,
        Success = 1,
        Created = 2,
        NoContent = 3,

        BadRequest = 4,
        Unauthorized = 5,
        Forbidden = 6,
        NotFound = 7,
        Conflict = 8,

        ServerInternalError = 9,
        DatabaseError = 10,
        ServiceUnavailable = 11,
        Timeout = 12,
        OperationCanceled = 13,

        ConnectionStable = 14,
        ConnectionUnstable = 15,
        ConnectionLost = 16,
        ServerMaintenance = 17,
        ClientVersionOutdated = 18,

        LoginSuccess = 19,
        InvalidCredentials = 20,
        AccountLocked = 21,
        AccountBanned = 22,
        AccountNotVerified = 23,
        AlreadyLoggedIn = 24,
        SessionExpired = 25,

        RegisterSuccess = 26,
        UserAlreadyExists = 27,
        EmailAlreadyRegistered = 28,
        InvalidUsernameFormat = 29,
        InvalidPasswordFormat = 30,
        InvalidEmailFormat = 31,
        RestrictedName = 32,

        VerificationCodeSent = 33,
        InvalidVerificationCode = 34,
        VerificationCodeExpired = 35,
        EmailVerifiedSuccess = 36,
        PasswordChangedSuccess = 37,
        PasswordMismatch = 38,

        FriendRequestSent = 39,
        FriendRequestAccepted = 40,
        FriendRequestRejected = 41,
        FriendRequestCanceled = 42,
        FriendRemoved = 43,
        FriendNotFound = 44,
        AlreadyFriends = 45,
        FriendRequestAlreadySent = 46,
        UserBlocked = 47,
        UserIsBlockingYou = 48,
        SelfFriendRequest = 49,
        FriendListFull = 50,

        MessageSent = 51,
        MessageTooLong = 52,
        SpamDetected = 53,
        InappropriateLanguage = 54,
        ChatMuted = 55,
        ChannelFull = 56,

        ReportReceived = 57,
        ReportLimitReached = 58,
        PlayerAlreadyReported = 59,

        JoinWorldSuccess = 60,
        MapInstanceFull = 61,
        MapNotFound = 62,
        PositionInvalid = 63,
        TeleportSuccess = 64,
        CannotEnterArea = 65,
        InstanceTimeout = 66,
        PlayerStuck = 67,

        InventoryLoaded = 68,
        InventoryFull = 69,
        ItemAdded = 70,
        ItemRemoved = 71,
        ItemNotFound = 72,
        ItemNotOwned = 73,
        ItemNotUsableHere = 74,
        ItemEquipped = 75,
        ItemUnequipped = 76,
        ItemConsumed = 77,
        CannotDropQuestItem = 78,
        StackLimitReached = 79,
        ItemBroken = 80,

        PurchaseSuccess = 81,
        InsufficientFunds = 82,
        ShopItemNotFound = 83,
        ShopItemOutOfStock = 84,
        ShopClosed = 85,
        TransactionFailed = 86,
        CosmeticAlreadyOwned = 87,
        SellSuccess = 88,
        ItemNotSellable = 89,
        TradeCanceled = 90,
        TradeSuccess = 91,

        LevelUp = 92,
        ExperienceGained = 93,
        SkillCooldown = 94,
        NotEnoughMana = 95,
        TargetInvalid = 96,
        TargetOutOfRange = 97,
        PlayerIsDead = 98,
        ReviveSuccess = 99,

        QuestAccepted = 100,
        QuestCompleted = 101,
        QuestRequirementsNotMet = 102,
        QuestLogFull = 103,
        QuestAbandoned = 104,

        ValidationError = 105,
        MissingRequiredField = 106,
        ValueOutOfRange = 107,
        InvalidCharacter = 108,
        TextTooShort = 109
    }
}
